[package]
name = 'Template'
version = '0.0.1'

[addresses]
package="_"

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
AptosTokenObjects = { local = "../framework/aptos-token-objects" }
