//# init --addresses Alice=0xf75daa73fc071f93593335eb9033da804777eb94491650dd3f095ce6f778acb6 Bob=0x9c3b634ac05d0af393e0f93b9b19b61e7cac1c519f566276aa0c6fd15dac12aa
//#      --private-keys Alice=56a26140eb233750cd14fb168c3eb4bd0782b099cde626ec8aff7f3cceb6364f Bob=952aaf3a98a27903dd078d76fc9e411740d2ae9dd9ecb87b96c7cd6b791ffc69
//#      --initial-coins 10000

//# run --script --signers Alice  --args @Bob 100



// Change publish network to testnet
// create signer account for the publishing module, use it
// create signer for the collection creator
// fund both accounts on testnet
// initialize_lilypad_v2, make sure max_mints_per_user is like 777 or smth


// tester wallet seed:
// bar mad lift farm omit wheat motor animal lock rain lizard shallow

//old one
// zero artwork judge insect chapter surge magic dose noise wheel mistake they

// 0x11637e8328263828fc96583fbdb4f263a0141d66a740f6a36017f685e71dd5ba, 0xac27bc01db6b4001a70f2273d3bf8a3877fd409a22cc2fd3a0eef534df789d94
// 0x8b1858c4ccf21024bb4b8dd23a8941fe763dbc3cb6750fc5a0bdb544e4aa18d0, 0xbc640853a95507db0fedaa04c82448b77c0be0d334d29f1fdc578db1ae6ebfdf
// minter1_address 0x3a25227bc36e1f564ddce1ae9ee8006bdcc7b0e3451f07c2a1c9a9648be9bd72, 0xceb6ab10bf7878af3858e9c7104fb37cd0dd1c1ab60df91710d143aa5d187524
// minter2_address 0x28f716ebd56a57d08764304e17fe3b8a32eff85b2a0c3b22206d713c5e3e41cf, 0xcee8ef03507ef65dff29253fa4664ebedf964b4d00a87db44813bdd4115177b0
// minter3_address 0xe05b094d6a6c97b2612d52927249707a8563191703277c17d829033950fd120a, 0x318a716226cdb8f1f6612be7dbf515e076f43a9fde06f92508b2a74e0e876b9d
// minter4_address 0x9755e1e3b25bff344d3c007eeac97709bce7ac3c2449333552cae90b2e1324f6, 0xc1500082e5b31026e3e3f109d4a1930370deba0c4a7c4f46c6ba7685071adb26
// minter5_address
// 0x396ab00c12ff73717575d6b09fbd0b7083a2e82496145e530c7ecb744fc8fcb0, 0x653b8b7364fe951c9daff8581e6bdf6ae0ad0a52a0c4f84f42a05117923c6082
// 0x26691df2350181149376311429cf3e1c0a2c8c0aa7283c650e33a36d658751bc, 0xc1eba48309c4d1da030a7011dbcb254f876aa3476adfa87f405f1566624ee57f


script {

	use std::string::{String, utf8};
	//use pond::lilypad_v2::{Self, BasicMint, WhitelistMint, VipMint};
	//use std::signer;
	//use aptos_token::token::{Self};
	//use std::vector::{Self};

	//use aptos_token::property_map::{Self};
	const BURNABLE_BY_CREATOR: vector<u8> = b"TOKEN_BURNABLE_BY_CREATOR";
	const TOKEN_DID_NOT_BECOME_BURNABLE: u64 = 7; // 0x7
	const COLLECTION_NAME: vector<u8> = b"Kreachers";
	const COLLECTION_MAXIMUM: u64 = 777;
	const TOKEN_NAME_BASE: vector<u8> = b"Kreacher #";
	const TOKEN_URI_BASE: vector<u8> = b"https://arweave.net/";
	const TOKEN_DESCRIPTION: vector<u8> = b"A mystic Kreacher known to inhabit the lands of InSilva.";
	const COLLECTION_URI: vector<u8> = b"https://arweave.net/CqFDEPEFSYmkkCskO1rm_zQztZx6NKnkt1KGi1Z5xwo";
	const COLLECTION_DESCRIPTION: vector<u8> = b"Who else lives in the forest that starts with a K? The KREACHERS of InSilva. These cute little balls of fur live amongst Elves and Humans who also play dress up. Yes you heard that right, the Kreachers love a good fashion game. Dress them as you see fit!";
	const COLLECTION_MUTABILITY: vector<bool> = vector<bool> [true, true, true];
	const TOKEN_MUTABILITY: vector<bool> = vector<bool> [ false, true, true, true, true ];
	const TREASURY_ADDRESS: address = @0x441d63bc5d378bd01c1021e2286515f9231879bd70f7881cb39c57ea34ee62b0;
	const ROYALTY_ADDRESS: address = @0x441d63bc5d378bd01c1021e2286515f9231879bd70f7881cb39c57ea34ee62b0;
	const ROYALTY_POINTS_DENOMINATOR: u64 = 100;
	const ROYALTY_POINTS_NUMERATOR: u64 = 5;
	const PRE_REVEAL_IMAGE: vector<u8> = b"https://arweave.net/jdCNSwTIa3PWYEruzUsTogZzR5wuWUHkKvEOqt5gohE";
	const LAUNCH_TIME: u64 = 1675033200000;
	const MINT_PRICE: u64 = 0;
	const WL_LAUNCH_TIME: u64 = 1675033200000;
	const WL_MINT_PRICE: u64 = 0;
	const VIP_LAUNCH_TIME: u64 = 1675033200000;
	const VIP_MINT_PRICE: u64 = 0;
	const MINTING_ENABLED: bool = true;

	const DAYS_TO_MS: u64 = 24 * 60 * 60 * 1000;
	const HOURS_TO_MS: u64 = 60 * 60 * 1000;
	const MINUTES_TO_MS: u64 = 60 * 1000;
	const SECONDS_TO_MS: u64 = 1000;

	const PROPERTY_MAP_STRING_TYPE: vector<u8> = b"0x1::string::String";

	const WRONG_CREATOR:  u64 = 123; // 0x7b

	fun create_swap_reveal(
		creator: &signer,
		//launch_time: u64,
		//additional_days: u64,
		//additional_hours: u64,
		//additional_minutes: u64,
		//additional_seconds: u64,
	) {
		//assert!(signer::address_of(creator) == @creator_address, WRONG_CREATOR);

		// let token_metadata_keys: vector<String> = vector<String> [
		// 		utf8(b"Background"),
		// 		utf8(b"Body"),
		// 		utf8(b"Eyes"),
		// 		utf8(b"Antler Polish"),
		// 		utf8(b"Shoes"),
		// 		utf8(b"Pants"),
		// 		utf8(b"Shirt"),
		// 		utf8(b"Hat"),
		// 		utf8(b"Eyewear"),
		// 		utf8(b"Antler Accessories"),
		// 	];

		// pond::swap_reveal::initialize_collection_clone(
		// 	creator,
		// 	utf8(COLLECTION_NAME),
		// 	utf8(COLLECTION_DESCRIPTION),
		// 	utf8(COLLECTION_URI),
		// 	777,
		// 	utf8(b"Kreacher #"),
		// 	vector<String> [],
		// 	LAUNCH_TIME,
		// );
		//let _ = launch_time;

			pond::swap_reveal::add_metadata(
				creator,
vector<String> [ utf8(b"https://arweave.net/HzYbbtDQKWhekhc7PWKiX_fdxLOMzRtKCvCSfDgJrag"),
utf8(b"https://arweave.net/7Tr21HMPqm2P9kGHkMrr0eNU6kfhlwNeRLOj30Rk8NQ"),
utf8(b"https://arweave.net/pYH4a902AUfG9CLLhZlIn6QHVREhYqPXjpOF1snvrcs"),
utf8(b"https://arweave.net/KkKScoJ4KgyptsqoAS6dC6k7DNLe70voPdtpRZbkKR4"),
utf8(b"https://arweave.net/7_FpljEXTPnNuwFaNnxpfKbqcICttw69CtaNuk2Shtk"),
utf8(b"https://arweave.net/vtDHWxBWcjLuvenVNxr0WwvyKYqeQqn9-V4CgNvef_8"),
utf8(b"https://arweave.net/ncYW3wmV9q4A3Lo9g5ZXjibjNoOYaUTUr29VWnv9qBM"),
utf8(b"https://arweave.net/30vNDc32upmAd0UerNk694Ot85FxZcnUeN8nrzcX5qU"),
utf8(b"https://arweave.net/mo5BShbLqUxle8yQPUaMPB1UfrKkgxkYhpb_oYjXpa8"),
utf8(b"https://arweave.net/dHRnbd7fYZwEMYn72j5aMjPStPdYU8RHXQDukErCp1U"),
utf8(b"https://arweave.net/pGvAB-s-Md9XPPwWEWtqcQ0pZa29vsJPUHpK1sdMkNY"),
utf8(b"https://arweave.net/TLYzg1Qrug-ToyeAQKqQ27g94MPFElZlqzKzpd81MI8"),
utf8(b"https://arweave.net/ThJo0h-Ng4e8JTjjILhzAOveUUKeS9Ahrobd0aBxZ_8"),
utf8(b"https://arweave.net/FoEOYgYv5YxcMAxi81psKGaiTssymKREtti_UQg1pD0"),
utf8(b"https://arweave.net/IIJ2gaOBFeJQTYx2zbcMgbKxgcnFuB89rQyHK6iDgBQ"),
utf8(b"https://arweave.net/5RHQG9L1HcCNBPcNoWXgIsSkLm8X_iWLawgA8oMsK30"),
utf8(b"https://arweave.net/Kzjgn0lhvsoLfg0Pbn8ACcOruJbavvJ0rk9oiuO9mAc"),
utf8(b"https://arweave.net/-BZ0aGfOpFV0uX3rHtJPdjgLffzmI-j-EWSFED87XgQ"),
utf8(b"https://arweave.net/r8Lb2MF0Zn6dbhq7SQle1BTSapULfiYZFvjvJj2yQDs"),
utf8(b"https://arweave.net/bA7SjJzBVJaSN6mj5WnYbM2b-z8v9-G2ShDk5SLz764"),
utf8(b"https://arweave.net/RJ32TM7GZ9NeouU3sQ1IAJxiV3qY5hDG6hfyX_G-SmE"),
utf8(b"https://arweave.net/d96TNpk3rvENMsbgt6pk5_8yOtOhUt-h7ltTuFscO20"),
utf8(b"https://arweave.net/Xi2jwfQeRU9zaS9dxAkgYyoGOc3ApqZCEhK85GnDm4U"),
utf8(b"https://arweave.net/x1XQCFtEykoEimU56CXWTfqWrh8aUd9mLPp43A3MLmA"),
utf8(b"https://arweave.net/d_fqtN_iOiLWgQ_MmX7Osi_jHfN3Fd3XUVjq8b65Nbk"),
utf8(b"https://arweave.net/ZN9I-ZkJr-3bEBbQvRKsBIBdBoES4pCJSKTumtUK8G8"),
utf8(b"https://arweave.net/QZQKvRC45VGDEbRlgvaPOgMv3Xq5V3X3gAX3iHmkjh4"),
utf8(b"https://arweave.net/ypyY35_vz0KR0BGL1B7T95_IZBAjI_eNMjw2u1oYzx0"),
utf8(b"https://arweave.net/9IQQ_bdk98dPaWBeQ49NRjNZKI4Z20zNG1TT4lTdUBs"),
utf8(b"https://arweave.net/T15zv1Z73i5VxDmcGWhSgiBIl6topmOpYMuSv33f-tI"),
utf8(b"https://arweave.net/KDX4jOH1JBbVciqBu1wmm91UbNcyRObxOlY608iKDho"),
utf8(b"https://arweave.net/7s7jE4IKlVHFOJloAE_dTCdI8zZjvYV0B-FLLbQmnTY"),
utf8(b"https://arweave.net/utQkSq8ij9nifvciGovnLagyOh9Kc0xJTMGdCVWjvUM"),
utf8(b"https://arweave.net/3Xr55lKnXF-BI_kF0WtVh2Fvkssmzub9pC9x4LNZLNY"),
utf8(b"https://arweave.net/z4dhH_8L2vLlLbml7Fj15OsNoyKH8t8PyX9lXyxv8ag"),
utf8(b"https://arweave.net/rcxFKLE7Xx5bzXDQQHRQ52TQhUYH0YySuY8A7dDFsUc"),
utf8(b"https://arweave.net/D4BQEmD8sj00NHXJaN0w-3iweAxcoVXyKEciXYN0yLI"),
utf8(b"https://arweave.net/qgTdq9srfZkmla10U1MC628bF2PImBej8-4HGGCbZG8"),
utf8(b"https://arweave.net/ERGOXnSvVVNtSgU8Bk8wZVqdfXLcdke2bRvLidu4ZII"),
utf8(b"https://arweave.net/j1wx4nW1B05w-cmvn-hhwXIzZk8mfxPuiXRs1AvCTO8"),
utf8(b"https://arweave.net/omIGyn4SwTI18r-ShjgIzrXz1R-eorUr3ipboKa__1A"),
utf8(b"https://arweave.net/TFbCsrDUX_d9Ny-0fLORKSeJc9nDB958_7GxusKK3YM"),
utf8(b"https://arweave.net/orsNZd1o5cs_M-4TIJ_MN8ORhCIbuNXsvggpRIwfRCw"),
utf8(b"https://arweave.net/w7f75App5yRzACRhEtvoaGdU1QP9VAsLQbh0vfIgloQ"),
utf8(b"https://arweave.net/iiqr5m9GThtjK6sUQF4-NCN5lvbsD2P3JyRN_RX8ZDQ"),
utf8(b"https://arweave.net/GCDIb8kAFfdMlED6j9EDOv1d3_FOyVeNoCyRmVBomh0"),
utf8(b"https://arweave.net/qEhZYtIy9oOL3I-MMqffm6JOG8mMrEPq4_nXoVMPej8"),
utf8(b"https://arweave.net/y_KLO7SwUWFgRydSsD-ZlX9Pi4mK4SjmVZqVHlDVmgk"),
utf8(b"https://arweave.net/yDXP5zMHGBY39xJZENahFV488GDrsFvhnBFRLv927rA"),
utf8(b"https://arweave.net/XViQeXQfhOf6NfDf4zUsv-Gnx265lmxNCFnQeaKM1rs"),
utf8(b"https://arweave.net/2rrEpk-PgYLmL_p5XKPU6xElOp6MwTedcEbpgkvT8Qo"),
utf8(b"https://arweave.net/A4z7OUcm5URFapB_WjVFhPVJrzRYnI14fFXIxDK2xXE"),
utf8(b"https://arweave.net/3gtfQkHf593UU-JYEckbn_xU6Y9Wmh9WfdeZUfkWFao"),
utf8(b"https://arweave.net/Hw3nQkbKoyM1hxmTJeY8ee7UajhzE-rVTWaNfaHEVfk"),
utf8(b"https://arweave.net/ezoDz_UJMUf8CC23GgVJ22CxGEycWqtJlmVKVmARAfM"),
utf8(b"https://arweave.net/zx0GFBfoiISgC1v9ROOTlZOTAn6KBJs2Mc6lETi7koE"),
utf8(b"https://arweave.net/7dBmb__vkOytzIpKw-PTmnR0_ZRyZ547k1v2OnLFwDw"),
utf8(b"https://arweave.net/nezbK4PngIwqM3Tm2tN-akK6ockeqxIPRf-j4Kv-1Pw"),
utf8(b"https://arweave.net/68X_QMrD0mw6ERVCO9fVAQj3kmI_ehKEV1Gqwys5V1g"),
utf8(b"https://arweave.net/zK4-ws78VXp_GdmmtDFsDWc3I8FzRfoczxt5UnGSQFY"),
utf8(b"https://arweave.net/lC8VmpWyzFZfYFI_XK1S5BEAFqa8rHQEKWGjURmHct8"),
utf8(b"https://arweave.net/s-sRvzbKuPbt9PvnU-Hcp4n8wZ7RtHP20z_G7rSuVfA"),
utf8(b"https://arweave.net/CmhbNWAk0VwAVnld6jMhAqxvo4upBnxsQw2X-sb67Q0"),
utf8(b"https://arweave.net/EzKbCKBcxykS_7r-0bybcT-SyrAYNPX_m29odNEBEk0"),
utf8(b"https://arweave.net/YD-JxOnWhBG0fHUdWuMjA6gcNTn9JxGGqc3dCvafxKI"),
utf8(b"https://arweave.net/H9j5KDzU2_ugv7j3ZF7hmR88y-0-_i8BIGzZmdfffcM"),
utf8(b"https://arweave.net/exBrjc08czRHh9j_LjYv2D3lr5TeOkB3-R6siSey9Dg"),
utf8(b"https://arweave.net/fKuWrWi8Foc7IJcYWH603ORi8F1y1n0bLRr5tM7eRn4"),
utf8(b"https://arweave.net/F5glRswXwSod2Oa56Ng_B-XCEcXDh02-uxMGY8DWrc0"),
utf8(b"https://arweave.net/2hP30sgAAVwa50-n1t_6U2JFTmT4lRjVDHJoWT_V7yE"),
utf8(b"https://arweave.net/ebbK6uCvcoqSHRcmL7Nhzta0MdGhndcWaEW_XfEkKBs"),
utf8(b"https://arweave.net/KVqURbUjoGv9AV2O6nWdv0qq5z0hFZxIZ9xJcqgin98"),
utf8(b"https://arweave.net/J7ffeDkSB0W4Ok0W1TXMp8VsyOvVRmYLxRWg-vq6LYU"),
utf8(b"https://arweave.net/2gf9QcAxMV2g7KLmHJ8RdNMiVNheiNZAPOKqKWRdekk"),
utf8(b"https://arweave.net/yxQFfSUhIgi3S22uqD7odXqCZaXEf075XL1tWmSwk4Y"),
utf8(b"https://arweave.net/PulAdrXAfDppj_Ki67mdaysgpE-pN6NJDdp3oN-ejGI"),
utf8(b"https://arweave.net/xOhwnPcdLOrk_F9nojm2jq1cp_C8QBMhBJtudL8kkJM"),
utf8(b"https://arweave.net/rgSlC9g5U_SNXXGwGYkoDMm7habC1yVHuMPbihbYMWI"),
utf8(b"https://arweave.net/WNv_w36JMCnhLUb8NagEhWKW-T3A7OLLimlq_dEfjnU"),
utf8(b"https://arweave.net/oqtD5wHw6HVmSAaq2dEr8yZITHO9oQlJJazNHeMad40"),
utf8(b"https://arweave.net/NlUdGoNLFK5sLf1OD3sd_mQ0f3SrljrZyjJ1J3M9wXc"),
utf8(b"https://arweave.net/sshgfm-Eqb-oI7oNQMd6yB7Sff4-dQfSo-Nb2-wG2a8"),
utf8(b"https://arweave.net/yJ4WJONnHumvv2RGDG337KQLw8PZ0S-ix_QsPMeHASc"),
utf8(b"https://arweave.net/dAw3W5df-Kn5RB-ByICveycDjMxCwwGNYMFP7EgO0cA"),
utf8(b"https://arweave.net/vZ-L77rpcjhI0kxmnxbWVf7X1bV4MTvCGpvjHPWnK0k"),
utf8(b"https://arweave.net/i0Ot4K-V3C9Ky8A9CBfWEzCtzuYeSIW9Ie1mI74fut0"),
utf8(b"https://arweave.net/RKPjcM7V7fTLuq7QzqpqSQ8ZwJtn96itgLXqI9eax0A"),
utf8(b"https://arweave.net/wYCDiwv3pFzErSJOhRFskozrpo0pTcJ8HPoVFjiKQBE"),
utf8(b"https://arweave.net/lJdGJ7p_ckmNmEU2OYJcujPt5fyZ0VSvXX0ED1ZMXrU"),
utf8(b"https://arweave.net/2GpR4UWWbmvJ6KbuNCF89St0m_haC-20oqJ2p-antvI"),
utf8(b"https://arweave.net/oBMtzGPF4reR_4wjwGtLcmRFRtvBVOCH0a4ahoGp4aI"),
utf8(b"https://arweave.net/VMDGj8amoEyetEkuXeDF2Rv1oEwc4d9ZhsJrMyRKpWU"),
utf8(b"https://arweave.net/s80TCZvhAZSXU0QgFuYNbysGhZmxm9A1dZf0GvmBf9M"),
utf8(b"https://arweave.net/dBcGdMgMDxnEwjAAngGvj_swVdJ3mLuviRoPNqS-psc"),
utf8(b"https://arweave.net/vrYSdkUyaZNi90_3Yj9AVGuB8qiypHmYeMJ3TtXNVTA"),
utf8(b"https://arweave.net/Grm_0nQfxyfBbMyQZbgnv37OYClIXoZIc-0zIaImCLE"),
utf8(b"https://arweave.net/NR7yjPeQ5fV8eqXjENs5MXnELxGtQG8GmDP1sVyxy38"),
utf8(b"https://arweave.net/ZZK0Gp3DAP2hGaH9XC-85P_LWt-2DsF3ZO2qM2ILWjI"),
utf8(b"https://arweave.net/WGYzTyytYlglXMPZtJxxC8A3075pwhw_dPyPxEevF_8"),
utf8(b"https://arweave.net/TL1waaEs0aHXcC5hQjBTS-esW9Zv53-YYIAh7S9TCBg"),
utf8(b"https://arweave.net/NvyNQPnvZoZsHv7rprksTpWJCf8pHgmIUCaldZ_u6Q0"),
utf8(b"https://arweave.net/zmTOMyn5BN6crT0EMHpiJEEDuG0OwXInEjWOfzBrS78"),
utf8(b"https://arweave.net/tzI65WTuV5ejfSwnyjzG_1fFfGAIOJDBVB463fsyNFo"),
utf8(b"https://arweave.net/cWRLv8kif6YK0kXJVoxYiIPpspQxCxFdyA2DZm7Dd88"),
utf8(b"https://arweave.net/1aPH_sY2n8txAQYQBRQavlQcIwwk3Yyk609zxSJNfrA"),
utf8(b"https://arweave.net/qTWFEiz43m4Ierj0BOxTdJDIyl9IU0xDaIrfK65X65M"),
utf8(b"https://arweave.net/heeV9e-YV2U8sJDvrMQIgecw0rb_gPxVAjJCJGDzzxA"),
utf8(b"https://arweave.net/Kfq31SoKjqhfasc1b3UQ9NUDUhK4zXfJcdZNp2PrG5M"),
utf8(b"https://arweave.net/BuTY15Knefj9hrqxBikh0c_gpRFAbqS5_s2jNpK3iqo"),
utf8(b"https://arweave.net/hhCf13dO1KeejfCfQjV1g4Myz4Hox6PynY6su4N5i_M"),
utf8(b"https://arweave.net/hQxTMB5XgCku8PstzPTDLe70Miuj_gpa2OhGcyVh560"),
 ],
vector<vector<String>> [ vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Eyewear"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"), utf8(b"Hat"), utf8(b"Eyewear"), utf8(b"Antler Accessories"),  ],
vector<String> [ utf8(b"Background"), utf8(b"Body"), utf8(b"Eyes"), utf8(b"Antler Polish"), utf8(b"Shoes"), utf8(b"Pants"), utf8(b"Shirt"),  ],
 ],
vector<vector<vector<u8>>> [ vector<vector<u8>> [ b"Lavender", b"White", b"Green", b"Red", b"Red Low", b"Pants Navy", b"Ghost Tee", b"Red Aviators", b"Vines",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Purple", b"Yellow", b"Purple", b"Red Low", b"Pants Navy", b"Dress Shirt", b"Vines",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Blue", b"Black Sneakers", b"Sweatpants Blue", b"Ghost Tee", b"Goggles",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Green", b"Rainboots", b"Cargo Pants Black", b"Wave Tee", b"Square Frames", b"Snow",  ],
vector<vector<u8>> [ b"Lavender", b"Orange", b"Red", b"Black Sneakers", b"Shorts Yellow", b"Snake Hoodie", b"Square Frames",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Purple", b"Blue", b"Black Sneakers", b"Sweatpants Blue", b"Wave Tee", b"Red Frames",  ],
vector<vector<u8>> [ b"Lavender", b"Orange", b"Yellow", b"Polkadot Low", b"Sweatpants Red", b"Wave Tee", b"Round Frames", b"Diamonds",  ],
vector<vector<u8>> [ b"Wheat", b"Orange", b"Green", b"Grey Sneakers", b"Sweatpants Red", b"Snake Hoodie", b"Crown", b"Red Frames",  ],
vector<vector<u8>> [ b"Lavender", b"Orange", b"Purple", b"Green Sandals", b"Sweatpants Red", b"Purple Drip Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Purple", b"Blue", b"Black Sneakers", b"Cargo Pants Green", b"Purple Drip Tee", b"Purple Beanie", b"Round Frames", b"Jewelry",  ],
vector<vector<u8>> [ b"Azur", b"Black", b"Yellow", b"Red", b"Black Sneakers", b"Cargo Pants Black", b"Yellow Hoodie", b"Red Aviators",  ],
vector<vector<u8>> [ b"Wheat", b"Blue", b"Red", b"Red Low", b"Cargo Pants Green", b"Yellow Hoodie", b"Jewelry",  ],
vector<vector<u8>> [ b"Lavender", b"Green", b"Red", b"Purple", b"Grey Sneakers", b"Pants Navy", b"Flame Tee", b"Crown", b"Vines",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Pink", b"Rainboots", b"Dress Pants", b"Pink Knit", b"Round Frames",  ],
vector<vector<u8>> [ b"Lavender", b"Purple", b"Red", b"Green Sandals", b"Cargo Pants Black", b"Wave Tee", b"Red Aviators",  ],
vector<vector<u8>> [ b"Azur", b"Black", b"Blue", b"Green Sandals", b"Cargo Pants Green", b"Flame Tee", b"Green Beanie", b"Round Frames",  ],
vector<vector<u8>> [ b"Foam", b"Green", b"Yellow", b"Red", b"Black Sneakers", b"Sweatpants Grey", b"Purple Drip Tee", b"Red Aviators", b"Jewelry",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Blue", b"Red Low", b"Pants Navy", b"Ghost Tee", b"Purple Beanie",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Pink", b"Purple", b"Red Low", b"Shorts Yellow", b"Ghost Tee",  ],
vector<vector<u8>> [ b"Foam", b"Purple", b"Purple", b"Red Boots", b"Cargo Pants Green", b"Snake Hoodie", b"Red Aviators", b"Vines",  ],
vector<vector<u8>> [ b"Foam", b"Blue", b"Green", b"Rainboots", b"Pants Navy", b"Tank", b"Green Beanie", b"Round Frames",  ],
vector<vector<u8>> [ b"Wheat", b"White", b"Yellow", b"Purple", b"Polkadot Low", b"Pants Navy", b"Dress Shirt", b"Purple Beanie", b"Round Frames", b"Vines",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Black", b"Blue", b"Blue", b"Black Sneakers", b"Pants Navy", b"Laser Shirt", b"Green Beanie", b"Vines",  ],
vector<vector<u8>> [ b"Azur", b"White", b"Red", b"Red Boots", b"Cargo Pants Green", b"Yellow Hoodie",  ],
vector<vector<u8>> [ b"Azur", b"Orange", b"Blue", b"Grey Sneakers", b"Pants Navy", b"Ghost Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Blue", b"Purple", b"Grey Sneakers", b"Cargo Pants Green", b"Laser Shirt", b"Purple Beanie", b"Square Frames", b"Ornaments",  ],
vector<vector<u8>> [ b"Foam", b"White", b"Pink", b"Red", b"Black Sneakers", b"Cargo Pants Black", b"Flame Tee", b"Red Aviators", b"Jewelry",  ],
vector<vector<u8>> [ b"Wheat", b"Blue", b"Red", b"Red", b"Grey Sneakers", b"Cargo Pants Black", b"Ghost Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Purple", b"Pink", b"Blue", b"Black Sneakers", b"Sweatpants Red", b"Laser Shirt", b"Red Aviators", b"Ornaments",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Blue", b"Red Boots", b"Sweatpants Grey", b"Ghost Tee", b"Green Beanie",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Red", b"Sandal Beige", b"Pants Navy", b"Flame Tee", b"Red Frames",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Pink", b"Purple", b"Polkadot Low", b"Sweatpants Grey", b"Ghost Tee", b"Goggles",  ],
vector<vector<u8>> [ b"Foam", b"Black", b"Purple", b"Red Low", b"Pants Navy", b"Graffiti Hoodie", b"Green Beanie", b"Diamonds",  ],
vector<vector<u8>> [ b"Wheat", b"Purple", b"Yellow", b"Rainboots", b"Pants Navy", b"Dress Shirt", b"Red Frames", b"Vines",  ],
vector<vector<u8>> [ b"Wheat", b"Green", b"Pink", b"Black Sneakers", b"Cargo Pants Green", b"Tank", b"Jewelry",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Blue", b"Red Boots", b"Pants Navy", b"Flame Tee",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Green", b"Black Sneakers", b"Cargo Pants Green", b"Flame Tee", b"Vines",  ],
vector<vector<u8>> [ b"Wheat", b"Purple", b"Pink", b"Rainboots", b"Shorts Yellow", b"Ghost Tee", b"Goggles", b"Ornaments",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Green", b"Black Sneakers", b"Pants Navy", b"Graffiti Hoodie", b"Green Beanie",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Purple", b"Blue", b"Grey Sneakers", b"Cargo Pants Black", b"Purple Drip Tee",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Green", b"Red", b"Polkadot Low", b"Sweatpants Grey", b"Tank", b"Purple Beanie",  ],
vector<vector<u8>> [ b"Foam", b"Orange", b"Yellow", b"Red Low", b"Sweatpants Grey", b"Dress Shirt", b"Goggles",  ],
vector<vector<u8>> [ b"Azur", b"White", b"Blue", b"Blue", b"Green Sandals", b"Cargo Pants Green", b"Ghost Tee", b"Green Beanie",  ],
vector<vector<u8>> [ b"Foam", b"Blue", b"Green", b"Purple", b"Rainboots", b"Dress Pants", b"Flame Tee", b"Green Beanie", b"Red Aviators", b"Vines",  ],
vector<vector<u8>> [ b"Foam", b"Blue", b"Yellow", b"Red", b"Red Boots", b"Shorts Yellow", b"Dress Shirt", b"Red Aviators", b"Diamonds",  ],
vector<vector<u8>> [ b"Foam", b"Purple", b"Green", b"Blue", b"Rainboots", b"Cargo Pants Black", b"Pink Knit", b"Green Beanie", b"Square Frames",  ],
vector<vector<u8>> [ b"Azur", b"Orange", b"Green", b"Red", b"Red Low", b"Cargo Pants Green", b"Purple Drip Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Green", b"Pink", b"Blue", b"Green Sandals", b"Sweatpants Grey", b"Ghost Tee", b"Goggles",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Green", b"Blue", b"Red", b"Polkadot Low", b"Pants Navy", b"Laser Shirt",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Green", b"Pink", b"Purple", b"Grey Sneakers", b"Cargo Pants Green", b"Purple Drip Tee",  ],
vector<vector<u8>> [ b"Lavender", b"Purple", b"Green", b"Rainboots", b"Cargo Pants Green", b"Dress Shirt", b"Crown", b"Round Frames", b"Vines",  ],
vector<vector<u8>> [ b"Azur", b"Black", b"Green", b"Black Sneakers", b"Sweatpants Grey", b"Purple Knit",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Yellow", b"Polkadot Low", b"Cargo Pants Green", b"Yellow Hoodie", b"Vines",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Green", b"Yellow", b"Purple", b"Green Sandals", b"Sweatpants Blue", b"Ghost Tee", b"Purple Beanie", b"Square Frames",  ],
vector<vector<u8>> [ b"Salmon Pink", b"White", b"Red", b"Polkadot Low", b"Sweatpants Blue", b"Ghost Tee", b"Crown", b"Vines",  ],
vector<vector<u8>> [ b"Lavender", b"Blue", b"Red", b"Red Low", b"Cargo Pants Green", b"Underwater Hoodie",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Purple", b"Black Sneakers", b"Cargo Pants Black", b"Ghost Tee", b"Round Frames",  ],
vector<vector<u8>> [ b"Azur", b"Orange", b"Purple", b"Black Sneakers", b"Sweatpants Blue", b"Laser Shirt",  ],
vector<vector<u8>> [ b"Salmon Pink", b"White", b"Blue", b"Rainboots", b"Dress Pants", b"Yellow Hoodie", b"Red Frames", b"Vines",  ],
vector<vector<u8>> [ b"Foam", b"Green", b"Red", b"Green Sandals", b"Cargo Pants Black", b"Pink Knit", b"Red Aviators",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Green", b"Blue", b"Red Low", b"Cargo Pants Green", b"Tank", b"Purple Beanie",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Blue", b"Black Sneakers", b"Cargo Pants Black", b"Laser Shirt", b"Square Frames",  ],
vector<vector<u8>> [ b"Lavender", b"Blue", b"Blue", b"Red", b"Rainboots", b"Pants Navy", b"Ghost Tee",  ],
vector<vector<u8>> [ b"Azur", b"Orange", b"Purple", b"Blue", b"Black Sneakers", b"Cargo Pants Black", b"Dress Shirt", b"Purple Beanie", b"Ornaments",  ],
vector<vector<u8>> [ b"Wheat", b"Green", b"Pink", b"Purple", b"Red Boots", b"Cargo Pants Green", b"Pink Knit", b"Purple Beanie", b"Round Red",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Red", b"Red", b"Black Sneakers", b"Shorts Purple", b"Ghost Tee", b"Purple Beanie", b"Red Frames",  ],
vector<vector<u8>> [ b"Foam", b"Blue", b"Green", b"Sandal Beige", b"Cargo Pants Black", b"Flame Tee", b"Jewelry",  ],
vector<vector<u8>> [ b"Lavender", b"Green", b"Pink", b"Red Low", b"Cargo Pants Green", b"Underwater Hoodie", b"Crown", b"Red Aviators",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Pink", b"Purple", b"Polkadot Low", b"Dress Pants", b"Flame Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Green", b"Green", b"Blue", b"Red Low", b"Shorts Purple", b"Ghost Tee", b"Goggles",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Green", b"Red Low", b"Cargo Pants Green", b"Tank", b"Snow",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Blue", b"Red", b"Red Low", b"Sweatpants Red", b"Laser Shirt",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Pink", b"Blue", b"Red Low", b"Sweatpants Grey", b"Laser Shirt", b"Crown", b"Diamonds",  ],
vector<vector<u8>> [ b"Azur", b"White", b"Yellow", b"Red Low", b"Shorts Yellow", b"Graffiti Hoodie", b"Green Beanie", b"Red Frames", b"Jewelry",  ],
vector<vector<u8>> [ b"Azur", b"White", b"Blue", b"Black Sneakers", b"Sweatpants Grey", b"Flame Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Blue", b"Red Low", b"Sweatpants Red", b"Laser Shirt",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Blue", b"Red", b"Polkadot Low", b"Pants Navy", b"Graffiti Hoodie", b"Goggles",  ],
vector<vector<u8>> [ b"Azur", b"Orange", b"Green", b"Purple", b"Red Low", b"Shorts Yellow", b"Laser Shirt", b"Snow",  ],
vector<vector<u8>> [ b"Wheat", b"Orange", b"Blue", b"Grey Sneakers", b"Cargo Pants Green", b"Purple Drip Tee", b"Red Aviators",  ],
vector<vector<u8>> [ b"Lavender", b"White", b"Blue", b"Red Boots", b"Shorts Purple", b"Dress Shirt", b"Red Aviators", b"Vines",  ],
vector<vector<u8>> [ b"Lavender", b"Blue", b"Pink", b"Red Low", b"Shorts Yellow", b"Flame Tee", b"Green Beanie", b"Red Frames",  ],
vector<vector<u8>> [ b"Lavender", b"Orange", b"Pink", b"Red Boots", b"Cargo Pants Black", b"Purple Drip Tee", b"Crown", b"Square Frames", b"Vines",  ],
vector<vector<u8>> [ b"Wheat", b"Blue", b"Blue", b"Purple", b"Grey Sneakers", b"Pants Navy", b"Pink Knit",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Green", b"Blue", b"Red Low", b"Cargo Pants Green", b"Tank", b"Diamonds",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Yellow", b"Blue", b"Sandal Beige", b"Pants Navy", b"Graffiti Hoodie", b"Goggles",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Green", b"Pink", b"Rainboots", b"Shorts Purple", b"Graffiti Hoodie",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Purple", b"Green", b"Red", b"Polkadot Low", b"Cargo Pants Green", b"Yellow Hoodie", b"Green Beanie",  ],
vector<vector<u8>> [ b"Azur", b"Black", b"Yellow", b"Red", b"Polkadot Low", b"Sweatpants Blue", b"Flame Tee", b"Red Aviators",  ],
vector<vector<u8>> [ b"Azur", b"Blue", b"Red", b"Polkadot Low", b"Cargo Pants Green", b"Ghost Tee",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Green", b"Purple", b"Red Low", b"Pants Navy", b"Flame Tee", b"Green Beanie", b"Square Frames",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Red", b"Blue", b"Red Low", b"Sweatpants Grey", b"Wave Tee", b"Red Aviators",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Orange", b"Green", b"Rainboots", b"Shorts Yellow", b"Tank",  ],
vector<vector<u8>> [ b"Wheat", b"Blue", b"Purple", b"Green Sandals", b"Cargo Pants Black", b"Dress Shirt", b"Crown",  ],
vector<vector<u8>> [ b"Lavender", b"White", b"Blue", b"Rainboots", b"Sweatpants Red", b"Laser Shirt", b"Red Frames", b"Ornaments",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Blue", b"Green", b"Red", b"Black Sneakers", b"Cargo Pants Green", b"Graffiti Hoodie", b"Goggles",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Red", b"Blue", b"Rainboots", b"Pants Navy", b"Ghost Tee", b"Red Frames",  ],
vector<vector<u8>> [ b"Azur", b"Green", b"Green", b"Red", b"Grey Sneakers", b"Shorts Purple", b"Graffiti Hoodie", b"Square Frames",  ],
vector<vector<u8>> [ b"Wheat", b"Orange", b"Yellow", b"Red Low", b"Cargo Pants Green", b"Flame Tee",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Blue", b"Red", b"Black Sneakers", b"Cargo Pants Green", b"Dress Shirt", b"Green Beanie", b"Jewelry",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Purple", b"Green", b"Red", b"Red Low", b"Cargo Pants Green", b"Laser Shirt", b"Purple Beanie", b"Red Frames",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Yellow", b"Black Sneakers", b"Sweatpants Grey", b"Laser Shirt", b"Vines",  ],
vector<vector<u8>> [ b"Wheat", b"Purple", b"Yellow", b"Polkadot Low", b"Sweatpants Grey", b"Snake Hoodie", b"Square Frames",  ],
vector<vector<u8>> [ b"Wheat", b"Purple", b"Blue", b"Blue", b"Black Sneakers", b"Sweatpants Grey", b"Ghost Tee",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Purple", b"Red", b"Polkadot Low", b"Sweatpants Blue", b"Laser Shirt", b"Red Aviators", b"Diamonds",  ],
vector<vector<u8>> [ b"Azur", b"White", b"Pink", b"Red", b"Red Low", b"Sweatpants Grey", b"Wave Tee",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Blue", b"Red", b"Red Low", b"Cargo Pants Black", b"Graffiti Hoodie",  ],
vector<vector<u8>> [ b"Lavender", b"Blue", b"Yellow", b"Black Sneakers", b"Sweatpants Grey", b"Ghost Tee", b"Purple Beanie", b"Round Frames", b"Jewelry",  ],
vector<vector<u8>> [ b"Azur", b"Purple", b"Purple", b"Sandal Beige", b"Sweatpants Blue", b"Ghost Tee", b"Red Aviators",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Purple", b"Green", b"Blue", b"Red Low", b"Cargo Pants Green", b"Dress Shirt", b"Red Frames",  ],
vector<vector<u8>> [ b"Salmon Pink", b"White", b"Green", b"Rainboots", b"Cargo Pants Green", b"Purple Drip Tee", b"Green Beanie", b"Square Frames", b"Vines",  ],
vector<vector<u8>> [ b"Salmon Pink", b"Black", b"Purple", b"Red", b"Rainboots", b"Dress Pants", b"Laser Shirt",  ],
 ],



			);
/*
		let token_names = vector<String> [
			utf8(b"Kreacher #0"),
			utf8(b"Kreacher #1"),
			utf8(b"Kreacher #2"),
			utf8(b"Kreacher #3"),
			utf8(b"Kreacher #4"),
			utf8(b"Kreacher #5"),
			utf8(b"Kreacher #6"),
			utf8(b"Kreacher #7"),
			utf8(b"Kreacher #8"),
			utf8(b"Kreacher #9"),
			utf8(b"Kreacher #10"),
			utf8(b"Kreacher #11"),
			utf8(b"Kreacher #12"),
			utf8(b"Kreacher #13"),
			utf8(b"Kreacher #14"),
			utf8(b"Kreacher #15"),
			utf8(b"Kreacher #16"),
			utf8(b"Kreacher #17"),
			utf8(b"Kreacher #18"),
			utf8(b"Kreacher #19"),
			utf8(b"Kreacher #20"),
			utf8(b"Kreacher #21"),
			utf8(b"Kreacher #22"),
			utf8(b"Kreacher #23"),
			utf8(b"Kreacher #24"),
			utf8(b"Kreacher #25"),
			utf8(b"Kreacher #26"),
			utf8(b"Kreacher #27"),
			utf8(b"Kreacher #28"),
			utf8(b"Kreacher #29"),
			utf8(b"Kreacher #30"),
			utf8(b"Kreacher #31"),
			utf8(b"Kreacher #32"),
			utf8(b"Kreacher #33"),
			utf8(b"Kreacher #34"),
			utf8(b"Kreacher #35"),
			utf8(b"Kreacher #36"),
			utf8(b"Kreacher #37"),
			utf8(b"Kreacher #38"),
			utf8(b"Kreacher #39"),
			utf8(b"Kreacher #40"),
			utf8(b"Kreacher #41"),
			utf8(b"Kreacher #42"),
			utf8(b"Kreacher #43"),
			utf8(b"Kreacher #44"),
			utf8(b"Kreacher #45"),
			utf8(b"Kreacher #46"),
			utf8(b"Kreacher #47"),
			utf8(b"Kreacher #48"),
			utf8(b"Kreacher #49"),
			utf8(b"Kreacher #50"),
			utf8(b"Kreacher #51"),
			utf8(b"Kreacher #52"),
			utf8(b"Kreacher #53"),
			utf8(b"Kreacher #54"),
			utf8(b"Kreacher #55"),
			utf8(b"Kreacher #56"),
			utf8(b"Kreacher #57"),
			utf8(b"Kreacher #58"),
			utf8(b"Kreacher #59"),
			utf8(b"Kreacher #60"),
			utf8(b"Kreacher #61"),
			utf8(b"Kreacher #62"),
			utf8(b"Kreacher #63"),
			utf8(b"Kreacher #64"),
			utf8(b"Kreacher #65"),
			utf8(b"Kreacher #66"),
			utf8(b"Kreacher #67"),
			utf8(b"Kreacher #68"),
			utf8(b"Kreacher #69"),
			utf8(b"Kreacher #70"),
			utf8(b"Kreacher #71"),
			utf8(b"Kreacher #72"),
			utf8(b"Kreacher #73"),
			utf8(b"Kreacher #74"),
			utf8(b"Kreacher #75"),
			utf8(b"Kreacher #76"),
			utf8(b"Kreacher #77"),
			utf8(b"Kreacher #78"),
			utf8(b"Kreacher #79"),
			utf8(b"Kreacher #80"),
			utf8(b"Kreacher #81"),
			utf8(b"Kreacher #82"),
			utf8(b"Kreacher #83"),
			utf8(b"Kreacher #84"),
			utf8(b"Kreacher #85"),
			utf8(b"Kreacher #86"),
			utf8(b"Kreacher #87"),
			utf8(b"Kreacher #88"),
			utf8(b"Kreacher #89"),
			utf8(b"Kreacher #90"),
			utf8(b"Kreacher #91"),
			utf8(b"Kreacher #92"),
			utf8(b"Kreacher #93"),
			utf8(b"Kreacher #94"),
			utf8(b"Kreacher #95"),
			utf8(b"Kreacher #96"),
			utf8(b"Kreacher #97"),
			utf8(b"Kreacher #98"),
			utf8(b"Kreacher #99"),
			utf8(b"Kreacher #100"),
			utf8(b"Kreacher #101"),
			utf8(b"Kreacher #102"),
			utf8(b"Kreacher #103"),
			utf8(b"Kreacher #104"),
			utf8(b"Kreacher #105"),
			utf8(b"Kreacher #106"),
			utf8(b"Kreacher #107"),
			utf8(b"Kreacher #108"),
			utf8(b"Kreacher #109"),
			utf8(b"Kreacher #110"),
			utf8(b"Kreacher #111"),
			utf8(b"Kreacher #112"),
			utf8(b"Kreacher #113"),
			utf8(b"Kreacher #114"),
			utf8(b"Kreacher #115"),
			utf8(b"Kreacher #116"),
			utf8(b"Kreacher #117"),
			utf8(b"Kreacher #118"),
			utf8(b"Kreacher #119"),
			utf8(b"Kreacher #120"),
			utf8(b"Kreacher #121"),
			utf8(b"Kreacher #122"),
			utf8(b"Kreacher #123"),
			utf8(b"Kreacher #124"),
			utf8(b"Kreacher #125"),
			utf8(b"Kreacher #126"),
			utf8(b"Kreacher #127"),
			utf8(b"Kreacher #128"),
			utf8(b"Kreacher #129"),
			utf8(b"Kreacher #130"),
			utf8(b"Kreacher #131"),
			utf8(b"Kreacher #132"),
			utf8(b"Kreacher #133"),
			utf8(b"Kreacher #134"),
			utf8(b"Kreacher #135"),
			utf8(b"Kreacher #136"),
			utf8(b"Kreacher #137"),
			utf8(b"Kreacher #138"),
			utf8(b"Kreacher #139"),
			utf8(b"Kreacher #140"),
			utf8(b"Kreacher #141"),
			utf8(b"Kreacher #142"),
			utf8(b"Kreacher #143"),
			utf8(b"Kreacher #144"),
			utf8(b"Kreacher #145"),
			utf8(b"Kreacher #146"),
			utf8(b"Kreacher #147"),
			utf8(b"Kreacher #148"),
			utf8(b"Kreacher #149"),
			utf8(b"Kreacher #150"),
			utf8(b"Kreacher #151"),
			utf8(b"Kreacher #152"),
			utf8(b"Kreacher #153"),
			utf8(b"Kreacher #154"),
			utf8(b"Kreacher #155"),
			utf8(b"Kreacher #156"),
			utf8(b"Kreacher #157"),
			utf8(b"Kreacher #158"),
			utf8(b"Kreacher #159"),
			utf8(b"Kreacher #160"),
			utf8(b"Kreacher #161"),
			utf8(b"Kreacher #162"),
			utf8(b"Kreacher #163"),
			utf8(b"Kreacher #164"),
			utf8(b"Kreacher #165"),
			utf8(b"Kreacher #166"),
			utf8(b"Kreacher #167"),
			utf8(b"Kreacher #168"),
			utf8(b"Kreacher #169"),
			utf8(b"Kreacher #170"),
			utf8(b"Kreacher #171"),
			utf8(b"Kreacher #172"),
			utf8(b"Kreacher #173"),
			utf8(b"Kreacher #174"),
			utf8(b"Kreacher #175"),
			utf8(b"Kreacher #176"),
			utf8(b"Kreacher #177"),
			utf8(b"Kreacher #178"),
			utf8(b"Kreacher #179"),
			utf8(b"Kreacher #180"),
			utf8(b"Kreacher #181"),
			utf8(b"Kreacher #182"),
			utf8(b"Kreacher #183"),
			utf8(b"Kreacher #184"),
			utf8(b"Kreacher #185"),
			utf8(b"Kreacher #186"),
			utf8(b"Kreacher #187"),
			utf8(b"Kreacher #188"),
			utf8(b"Kreacher #189"),
			utf8(b"Kreacher #190"),
			utf8(b"Kreacher #191"),
			utf8(b"Kreacher #192"),
			utf8(b"Kreacher #193"),
			utf8(b"Kreacher #194"),
			utf8(b"Kreacher #195"),
			utf8(b"Kreacher #196"),
			utf8(b"Kreacher #197"),
			utf8(b"Kreacher #198"),
			utf8(b"Kreacher #199"),
			utf8(b"Kreacher #200"),
			utf8(b"Kreacher #201"),
			utf8(b"Kreacher #202"),
			utf8(b"Kreacher #203"),
			utf8(b"Kreacher #204"),
			utf8(b"Kreacher #205"),
			utf8(b"Kreacher #206"),
			utf8(b"Kreacher #207"),
			utf8(b"Kreacher #208"),
			utf8(b"Kreacher #209"),
			utf8(b"Kreacher #210"),
			utf8(b"Kreacher #211"),
			utf8(b"Kreacher #212"),
			utf8(b"Kreacher #213"),
			utf8(b"Kreacher #214"),
			utf8(b"Kreacher #215"),
			utf8(b"Kreacher #216"),
			utf8(b"Kreacher #217"),
			utf8(b"Kreacher #218"),
			utf8(b"Kreacher #219"),
			utf8(b"Kreacher #220"),
			utf8(b"Kreacher #221"),
			utf8(b"Kreacher #222"),
			utf8(b"Kreacher #223"),
			utf8(b"Kreacher #224"),
			utf8(b"Kreacher #225"),
			utf8(b"Kreacher #226"),
			utf8(b"Kreacher #227"),
			utf8(b"Kreacher #228"),
			utf8(b"Kreacher #229"),
			utf8(b"Kreacher #230"),
			utf8(b"Kreacher #231"),
			utf8(b"Kreacher #232"),
			utf8(b"Kreacher #233"),
			utf8(b"Kreacher #234"),
			utf8(b"Kreacher #235"),
			utf8(b"Kreacher #236"),
			utf8(b"Kreacher #237"),
			utf8(b"Kreacher #238"),
			utf8(b"Kreacher #239"),
			utf8(b"Kreacher #240"),
			utf8(b"Kreacher #241"),
			utf8(b"Kreacher #242"),
			utf8(b"Kreacher #243"),
			utf8(b"Kreacher #244"),
			utf8(b"Kreacher #245"),
			utf8(b"Kreacher #246"),
			utf8(b"Kreacher #247"),
			utf8(b"Kreacher #248"),
			utf8(b"Kreacher #249"),
			utf8(b"Kreacher #250"),
			utf8(b"Kreacher #251"),
			utf8(b"Kreacher #252"),
			utf8(b"Kreacher #253"),
			utf8(b"Kreacher #254"),
			utf8(b"Kreacher #255"),
			utf8(b"Kreacher #256"),
			utf8(b"Kreacher #257"),
			utf8(b"Kreacher #258"),
			utf8(b"Kreacher #259"),
			utf8(b"Kreacher #260"),
			utf8(b"Kreacher #261"),
			utf8(b"Kreacher #262"),
			utf8(b"Kreacher #263"),
			utf8(b"Kreacher #264"),
			utf8(b"Kreacher #265"),
			utf8(b"Kreacher #266"),
			utf8(b"Kreacher #267"),
			utf8(b"Kreacher #268"),
			utf8(b"Kreacher #269"),
			utf8(b"Kreacher #270"),
			utf8(b"Kreacher #271"),
			utf8(b"Kreacher #272"),
			utf8(b"Kreacher #273"),
			utf8(b"Kreacher #274"),
			utf8(b"Kreacher #275"),
			utf8(b"Kreacher #276"),
			utf8(b"Kreacher #277"),
			utf8(b"Kreacher #278"),
			utf8(b"Kreacher #279"),
			utf8(b"Kreacher #280"),
			utf8(b"Kreacher #281"),
			utf8(b"Kreacher #282"),
			utf8(b"Kreacher #283"),
			utf8(b"Kreacher #284"),
			utf8(b"Kreacher #285"),
			utf8(b"Kreacher #286"),
			utf8(b"Kreacher #287"),
			utf8(b"Kreacher #288"),
			utf8(b"Kreacher #289"),
			utf8(b"Kreacher #290"),
			utf8(b"Kreacher #291"),
			utf8(b"Kreacher #292"),
			utf8(b"Kreacher #293"),
			utf8(b"Kreacher #294"),
			utf8(b"Kreacher #295"),
			utf8(b"Kreacher #296"),
			utf8(b"Kreacher #297"),
			utf8(b"Kreacher #298"),
			utf8(b"Kreacher #299"),
			utf8(b"Kreacher #300"),
			utf8(b"Kreacher #301"),
			utf8(b"Kreacher #302"),
			utf8(b"Kreacher #303"),
			utf8(b"Kreacher #304"),
			utf8(b"Kreacher #305"),
			utf8(b"Kreacher #306"),
			utf8(b"Kreacher #307"),
			utf8(b"Kreacher #308"),
			utf8(b"Kreacher #309"),
			utf8(b"Kreacher #310"),
			utf8(b"Kreacher #311"),
			utf8(b"Kreacher #312"),
			utf8(b"Kreacher #313"),
			utf8(b"Kreacher #314"),
			utf8(b"Kreacher #315"),
			utf8(b"Kreacher #316"),
			utf8(b"Kreacher #317"),
			utf8(b"Kreacher #318"),
			utf8(b"Kreacher #319"),
			utf8(b"Kreacher #320"),
			utf8(b"Kreacher #321"),
			utf8(b"Kreacher #322"),
			utf8(b"Kreacher #323"),
			utf8(b"Kreacher #324"),
			utf8(b"Kreacher #325"),
			utf8(b"Kreacher #326"),
			utf8(b"Kreacher #327"),
			utf8(b"Kreacher #328"),
			utf8(b"Kreacher #329"),
			utf8(b"Kreacher #330"),
			utf8(b"Kreacher #331"),
			utf8(b"Kreacher #332"),
			utf8(b"Kreacher #333"),
			utf8(b"Kreacher #334"),
			utf8(b"Kreacher #335"),
			utf8(b"Kreacher #336"),
			utf8(b"Kreacher #337"),
			utf8(b"Kreacher #338"),
			utf8(b"Kreacher #339"),
			utf8(b"Kreacher #340"),
			utf8(b"Kreacher #341"),
			utf8(b"Kreacher #342"),
			utf8(b"Kreacher #343"),
			utf8(b"Kreacher #344"),
			utf8(b"Kreacher #345"),
			utf8(b"Kreacher #346"),
			utf8(b"Kreacher #347"),
			utf8(b"Kreacher #348"),
			utf8(b"Kreacher #349"),
			utf8(b"Kreacher #350"),
			utf8(b"Kreacher #351"),
			utf8(b"Kreacher #352"),
			utf8(b"Kreacher #353"),
			utf8(b"Kreacher #354"),
			utf8(b"Kreacher #355"),
			utf8(b"Kreacher #356"),
			utf8(b"Kreacher #357"),
			utf8(b"Kreacher #358"),
			utf8(b"Kreacher #359"),
			utf8(b"Kreacher #360"),
			utf8(b"Kreacher #361"),
			utf8(b"Kreacher #362"),
			utf8(b"Kreacher #363"),
			utf8(b"Kreacher #364"),
			utf8(b"Kreacher #365"),
			utf8(b"Kreacher #366"),
			utf8(b"Kreacher #367"),
			utf8(b"Kreacher #368"),
			utf8(b"Kreacher #369"),
			utf8(b"Kreacher #370"),
			utf8(b"Kreacher #371"),
			utf8(b"Kreacher #372"),
			utf8(b"Kreacher #373"),
			utf8(b"Kreacher #374"),
			utf8(b"Kreacher #375"),
			utf8(b"Kreacher #376"),
			utf8(b"Kreacher #377"),
			utf8(b"Kreacher #378"),
			utf8(b"Kreacher #379"),
			utf8(b"Kreacher #380"),
			utf8(b"Kreacher #381"),
			utf8(b"Kreacher #382"),
			utf8(b"Kreacher #383"),
			utf8(b"Kreacher #384"),
			utf8(b"Kreacher #385"),
			utf8(b"Kreacher #386"),
			utf8(b"Kreacher #387"),
			utf8(b"Kreacher #388"),
			utf8(b"Kreacher #389"),
			utf8(b"Kreacher #390"),
			utf8(b"Kreacher #391"),
			utf8(b"Kreacher #392"),
			utf8(b"Kreacher #393"),
			utf8(b"Kreacher #394"),
			utf8(b"Kreacher #395"),
			utf8(b"Kreacher #396"),
			utf8(b"Kreacher #397"),
			utf8(b"Kreacher #398"),
			utf8(b"Kreacher #399"),
			utf8(b"Kreacher #400"),
			utf8(b"Kreacher #401"),
			utf8(b"Kreacher #402"),
			utf8(b"Kreacher #403"),
			utf8(b"Kreacher #404"),
			utf8(b"Kreacher #405"),
			utf8(b"Kreacher #406"),
			utf8(b"Kreacher #407"),
			utf8(b"Kreacher #408"),
			utf8(b"Kreacher #409"),
			utf8(b"Kreacher #410"),
			utf8(b"Kreacher #411"),
			utf8(b"Kreacher #412"),
			utf8(b"Kreacher #413"),
			utf8(b"Kreacher #414"),
			utf8(b"Kreacher #415"),
			utf8(b"Kreacher #416"),
			utf8(b"Kreacher #417"),
			utf8(b"Kreacher #418"),
			utf8(b"Kreacher #419"),
			utf8(b"Kreacher #420"),
			utf8(b"Kreacher #421"),
			utf8(b"Kreacher #422"),
			utf8(b"Kreacher #423"),
			utf8(b"Kreacher #424"),
			utf8(b"Kreacher #425"),
			utf8(b"Kreacher #426"),
			utf8(b"Kreacher #427"),
			utf8(b"Kreacher #428"),
			utf8(b"Kreacher #429"),
			utf8(b"Kreacher #430"),
			utf8(b"Kreacher #431"),
			utf8(b"Kreacher #432"),
			utf8(b"Kreacher #433"),
			utf8(b"Kreacher #434"),
			utf8(b"Kreacher #435"),
			utf8(b"Kreacher #436"),
			utf8(b"Kreacher #437"),
			utf8(b"Kreacher #438"),
			utf8(b"Kreacher #439"),
			utf8(b"Kreacher #440"),
			utf8(b"Kreacher #441"),
			utf8(b"Kreacher #442"),
			utf8(b"Kreacher #443"),
			utf8(b"Kreacher #444"),
			utf8(b"Kreacher #445"),
			utf8(b"Kreacher #446"),
			utf8(b"Kreacher #447"),
			utf8(b"Kreacher #448"),
			utf8(b"Kreacher #449"),
			utf8(b"Kreacher #450"),
			utf8(b"Kreacher #451"),
			utf8(b"Kreacher #452"),
			utf8(b"Kreacher #453"),
			utf8(b"Kreacher #454"),
			utf8(b"Kreacher #455"),
			utf8(b"Kreacher #456"),
			utf8(b"Kreacher #457"),
			utf8(b"Kreacher #458"),
			utf8(b"Kreacher #459"),
			utf8(b"Kreacher #460"),
			utf8(b"Kreacher #461"),
			utf8(b"Kreacher #462"),
			utf8(b"Kreacher #463"),
			utf8(b"Kreacher #464"),
			utf8(b"Kreacher #465"),
			utf8(b"Kreacher #466"),
			utf8(b"Kreacher #467"),
			utf8(b"Kreacher #468"),
			utf8(b"Kreacher #469"),
			utf8(b"Kreacher #470"),
			utf8(b"Kreacher #471"),
			utf8(b"Kreacher #472"),
			utf8(b"Kreacher #473"),
			utf8(b"Kreacher #474"),
			utf8(b"Kreacher #475"),
			utf8(b"Kreacher #476"),
			utf8(b"Kreacher #477"),
			utf8(b"Kreacher #478"),
			utf8(b"Kreacher #479"),
			utf8(b"Kreacher #480"),
			utf8(b"Kreacher #481"),
			utf8(b"Kreacher #482"),
			utf8(b"Kreacher #483"),
			utf8(b"Kreacher #484"),
			utf8(b"Kreacher #485"),
			utf8(b"Kreacher #486"),
			utf8(b"Kreacher #487"),
			utf8(b"Kreacher #488"),
			utf8(b"Kreacher #489"),
			utf8(b"Kreacher #490"),
			utf8(b"Kreacher #491"),
			utf8(b"Kreacher #492"),
			utf8(b"Kreacher #493"),
			utf8(b"Kreacher #494"),
			utf8(b"Kreacher #495"),
			utf8(b"Kreacher #496"),
			utf8(b"Kreacher #497"),
			utf8(b"Kreacher #498"),
			utf8(b"Kreacher #499"),
			utf8(b"Kreacher #500"),
			utf8(b"Kreacher #501"),
			utf8(b"Kreacher #502"),
			utf8(b"Kreacher #503"),
			utf8(b"Kreacher #504"),
			utf8(b"Kreacher #505"),
			utf8(b"Kreacher #506"),
			utf8(b"Kreacher #507"),
			utf8(b"Kreacher #508"),
			utf8(b"Kreacher #509"),
			utf8(b"Kreacher #510"),
			utf8(b"Kreacher #511"),
			utf8(b"Kreacher #512"),
			utf8(b"Kreacher #513"),
			utf8(b"Kreacher #514"),
			utf8(b"Kreacher #515"),
			utf8(b"Kreacher #516"),
			utf8(b"Kreacher #517"),
			utf8(b"Kreacher #518"),
			utf8(b"Kreacher #519"),
			utf8(b"Kreacher #520"),
			utf8(b"Kreacher #521"),
			utf8(b"Kreacher #522"),
			utf8(b"Kreacher #523"),
			utf8(b"Kreacher #524"),
			utf8(b"Kreacher #525"),
			utf8(b"Kreacher #526"),
			utf8(b"Kreacher #527"),
			utf8(b"Kreacher #528"),
			utf8(b"Kreacher #529"),
			utf8(b"Kreacher #530"),
			utf8(b"Kreacher #531"),
			utf8(b"Kreacher #532"),
			utf8(b"Kreacher #533"),
			utf8(b"Kreacher #534"),
			utf8(b"Kreacher #535"),
			utf8(b"Kreacher #536"),
			utf8(b"Kreacher #537"),
			utf8(b"Kreacher #538"),
			utf8(b"Kreacher #539"),
			utf8(b"Kreacher #540"),
			utf8(b"Kreacher #541"),
			utf8(b"Kreacher #542"),
			utf8(b"Kreacher #543"),
			utf8(b"Kreacher #544"),
			utf8(b"Kreacher #545"),
			utf8(b"Kreacher #546"),
			utf8(b"Kreacher #547"),
			utf8(b"Kreacher #548"),
			utf8(b"Kreacher #549"),
			utf8(b"Kreacher #550"),
			utf8(b"Kreacher #551"),
			utf8(b"Kreacher #552"),
			utf8(b"Kreacher #553"),
			utf8(b"Kreacher #554"),
			utf8(b"Kreacher #555"),
			utf8(b"Kreacher #556"),
			utf8(b"Kreacher #557"),
			utf8(b"Kreacher #558"),
			utf8(b"Kreacher #559"),
			utf8(b"Kreacher #560"),
			utf8(b"Kreacher #561"),
			utf8(b"Kreacher #562"),
			utf8(b"Kreacher #563"),
			utf8(b"Kreacher #564"),
			utf8(b"Kreacher #565"),
			utf8(b"Kreacher #566"),
			utf8(b"Kreacher #567"),
			utf8(b"Kreacher #568"),
			utf8(b"Kreacher #569"),
			utf8(b"Kreacher #570"),
			utf8(b"Kreacher #571"),
			utf8(b"Kreacher #572"),
			utf8(b"Kreacher #573"),
			utf8(b"Kreacher #574"),
			utf8(b"Kreacher #575"),
			utf8(b"Kreacher #576"),
			utf8(b"Kreacher #577"),
			utf8(b"Kreacher #578"),
			utf8(b"Kreacher #579"),
			utf8(b"Kreacher #580"),
			utf8(b"Kreacher #581"),
			utf8(b"Kreacher #582"),
			utf8(b"Kreacher #583"),
			utf8(b"Kreacher #584"),
			utf8(b"Kreacher #585"),
			utf8(b"Kreacher #586"),
			utf8(b"Kreacher #587"),
			utf8(b"Kreacher #588"),
			utf8(b"Kreacher #589"),
			utf8(b"Kreacher #590"),
			utf8(b"Kreacher #591"),
			utf8(b"Kreacher #592"),
			utf8(b"Kreacher #593"),
			utf8(b"Kreacher #594"),
			utf8(b"Kreacher #595"),
			utf8(b"Kreacher #596"),
			utf8(b"Kreacher #597"),
			utf8(b"Kreacher #598"),
			utf8(b"Kreacher #599"),
			utf8(b"Kreacher #600"),
			utf8(b"Kreacher #601"),
			utf8(b"Kreacher #602"),
			utf8(b"Kreacher #603"),
			utf8(b"Kreacher #604"),
			utf8(b"Kreacher #605"),
			utf8(b"Kreacher #606"),
			utf8(b"Kreacher #607"),
			utf8(b"Kreacher #608"),
			utf8(b"Kreacher #609"),
			utf8(b"Kreacher #610"),
			utf8(b"Kreacher #611"),
			utf8(b"Kreacher #612"),
			utf8(b"Kreacher #613"),
			utf8(b"Kreacher #614"),
			utf8(b"Kreacher #615"),
			utf8(b"Kreacher #616"),
			utf8(b"Kreacher #617"),
			utf8(b"Kreacher #618"),
			utf8(b"Kreacher #619"),
			utf8(b"Kreacher #620"),
			utf8(b"Kreacher #621"),
			utf8(b"Kreacher #622"),
			utf8(b"Kreacher #623"),
			utf8(b"Kreacher #624"),
			utf8(b"Kreacher #625"),
			utf8(b"Kreacher #626"),
			utf8(b"Kreacher #627"),
			utf8(b"Kreacher #628"),
			utf8(b"Kreacher #629"),
			utf8(b"Kreacher #630"),
			utf8(b"Kreacher #631"),
			utf8(b"Kreacher #632"),
			utf8(b"Kreacher #633"),
			utf8(b"Kreacher #634"),
			utf8(b"Kreacher #635"),
			utf8(b"Kreacher #636"),
			utf8(b"Kreacher #637"),
			utf8(b"Kreacher #638"),
			utf8(b"Kreacher #639"),
			utf8(b"Kreacher #640"),
			utf8(b"Kreacher #641"),
			utf8(b"Kreacher #642"),
			utf8(b"Kreacher #643"),
			utf8(b"Kreacher #644"),
			utf8(b"Kreacher #645"),
			utf8(b"Kreacher #646"),
			utf8(b"Kreacher #647"),
			utf8(b"Kreacher #648"),
			utf8(b"Kreacher #649"),
			utf8(b"Kreacher #650"),
			utf8(b"Kreacher #651"),
			utf8(b"Kreacher #652"),
			utf8(b"Kreacher #653"),
			utf8(b"Kreacher #654"),
			utf8(b"Kreacher #655"),
			utf8(b"Kreacher #656"),
			utf8(b"Kreacher #657"),
			utf8(b"Kreacher #658"),
			utf8(b"Kreacher #659"),
			utf8(b"Kreacher #660"),
			utf8(b"Kreacher #661"),
			utf8(b"Kreacher #662"),
			utf8(b"Kreacher #663"),
			utf8(b"Kreacher #664"),
			utf8(b"Kreacher #665"),
			utf8(b"Kreacher #666"),
			utf8(b"Kreacher #667"),
			utf8(b"Kreacher #668"),
			utf8(b"Kreacher #669"),
			utf8(b"Kreacher #670"),
			utf8(b"Kreacher #671"),
			utf8(b"Kreacher #672"),
			utf8(b"Kreacher #673"),
			utf8(b"Kreacher #674"),
			utf8(b"Kreacher #675"),
			utf8(b"Kreacher #676"),
			utf8(b"Kreacher #677"),
			utf8(b"Kreacher #678"),
			utf8(b"Kreacher #679"),
			utf8(b"Kreacher #680"),
			utf8(b"Kreacher #681"),
			utf8(b"Kreacher #682"),
			utf8(b"Kreacher #683"),
			utf8(b"Kreacher #684"),
			utf8(b"Kreacher #685"),
			utf8(b"Kreacher #686"),
			utf8(b"Kreacher #687"),
			utf8(b"Kreacher #688"),
			utf8(b"Kreacher #689"),
			utf8(b"Kreacher #690"),
			utf8(b"Kreacher #691"),
			utf8(b"Kreacher #692"),
			utf8(b"Kreacher #693"),
			utf8(b"Kreacher #694"),
			utf8(b"Kreacher #695"),
			utf8(b"Kreacher #696"),
			utf8(b"Kreacher #697"),
			utf8(b"Kreacher #698"),
			utf8(b"Kreacher #699"),
			utf8(b"Kreacher #700"),
			utf8(b"Kreacher #701"),
			utf8(b"Kreacher #702"),
			utf8(b"Kreacher #703"),
			utf8(b"Kreacher #704"),
			utf8(b"Kreacher #705"),
			utf8(b"Kreacher #706"),
			utf8(b"Kreacher #707"),
			utf8(b"Kreacher #708"),
			utf8(b"Kreacher #709"),
			utf8(b"Kreacher #710"),
			utf8(b"Kreacher #711"),
			utf8(b"Kreacher #712"),
			utf8(b"Kreacher #713"),
			utf8(b"Kreacher #714"),
			utf8(b"Kreacher #715"),
			utf8(b"Kreacher #716"),
			utf8(b"Kreacher #717"),
			utf8(b"Kreacher #718"),
			utf8(b"Kreacher #719"),
			utf8(b"Kreacher #720"),
			utf8(b"Kreacher #721"),
			utf8(b"Kreacher #722"),
			utf8(b"Kreacher #723"),
			utf8(b"Kreacher #724"),
			utf8(b"Kreacher #725"),
			utf8(b"Kreacher #726"),
			utf8(b"Kreacher #727"),
			utf8(b"Kreacher #728"),
			utf8(b"Kreacher #729"),
			utf8(b"Kreacher #730"),
			utf8(b"Kreacher #731"),
			utf8(b"Kreacher #732"),
			utf8(b"Kreacher #733"),
			utf8(b"Kreacher #734"),
			utf8(b"Kreacher #735"),
			utf8(b"Kreacher #736"),
			utf8(b"Kreacher #737"),
			utf8(b"Kreacher #738"),
			utf8(b"Kreacher #739"),
			utf8(b"Kreacher #740"),
			utf8(b"Kreacher #741"),
			utf8(b"Kreacher #742"),
			utf8(b"Kreacher #743"),
			utf8(b"Kreacher #744"),
			utf8(b"Kreacher #745"),
			utf8(b"Kreacher #746"),
			utf8(b"Kreacher #747"),
			utf8(b"Kreacher #748"),
			utf8(b"Kreacher #749"),
			utf8(b"Kreacher #750"),
			utf8(b"Kreacher #751"),
			utf8(b"Kreacher #752"),
			utf8(b"Kreacher #753"),
			utf8(b"Kreacher #754"),
			utf8(b"Kreacher #755"),
			utf8(b"Kreacher #756"),
			utf8(b"Kreacher #757"),
			utf8(b"Kreacher #758"),
			utf8(b"Kreacher #759"),
			utf8(b"Kreacher #760"),
			utf8(b"Kreacher #761"),
			utf8(b"Kreacher #762"),
			utf8(b"Kreacher #763"),
			utf8(b"Kreacher #764"),
			utf8(b"Kreacher #765"),
			utf8(b"Kreacher #766"),
			utf8(b"Kreacher #767"),
			utf8(b"Kreacher #768"),
			utf8(b"Kreacher #769"),
			utf8(b"Kreacher #770"),
			utf8(b"Kreacher #771"),
			utf8(b"Kreacher #772"),
			utf8(b"Kreacher #773"),
			utf8(b"Kreacher #774"),
			utf8(b"Kreacher #775"),
			utf8(b"Kreacher #776"),
		];


		let _ = token_names;
*/


		//let _ = additional_days;
		//let _ = additional_hours;
		//let _ = additional_minutes;
		//let _ = additional_seconds;

		// pond::lilypad_v2::make_tokens_burnable(
		// 	creator,
		// 	utf8(COLLECTION_NAME),
		// 	token_names,
		// );


		// let new_launch_time = launch_time + additional_days * DAYS_TO_MS +
		// 								additional_hours * HOURS_TO_MS +
		// 								additional_minutes * MINUTES_TO_MS +
		// 								additional_seconds * SECONDS_TO_MS;

		// pond::swap_reveal::update_launch_time(
		// 	creator,
		// 	new_launch_time,
		// );
	}
}

//# view --address Bob  --resource 0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>
