[package]
name = 'ambassador_token'
version = '1.0.0'

[addresses]
ambassador_token = "_"

[dependencies]
AptosFramework = { local = "../../../../framework/aptos-framework" }
AptosTokenObjects = { local = "../../../../framework/aptos-token-objects" }
