name: "*run execution-performance reusable workflow"

on:
  # This allows the workflow to be triggered from another workflow
  workflow_call:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test.
      RUNNER_NAME:
        required: false
        default: executor-benchmark-runner 
        type: string
  # This allows the workflow to be triggered manually from the Github UI or CLI
  # NOTE: because the "number" type is not supported, we default to 720 minute timeout
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: true
        type: string
        description: The git SHA1 to test.
      RUNNER_NAME:
        required: false
        default: executor-benchmark-runner 
        type: choice
        options:
        - spot-runner
        - executor-benchmark-runner
        description: The name of the runner to use for the test.

jobs:
  sequential-execution-performance:
    timeout-minutes: 30
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

      - name: Run sequential execution benchmark in performance build mode
        shell: bash
        run: testsuite/sequential_execution_performance.py

  parallel-execution-performance:
    timeout-minutes: 60
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

      - name: Run parallel execution benchmark in performance build mode
        shell: bash
        run: testsuite/parallel_execution_performance.py

  single-node-performance:
    timeout-minutes: 60
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

      - name: Run single node execution benchmark in performance build mode
        shell: bash
        run: TABULATE_INSTALL=lib-only pip install tabulate && testsuite/single_node_performance.py
